import { createInvitation, setPublish } from '@/app/actions/invitations'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { invitations } from '@/lib/db/schema'
import { desc, eq } from 'drizzle-orm'
import { headers } from 'next/headers'
import Link from 'next/link'
import { ExternalLink, Plus, Settings2 } from 'lucide-react'

export default async function DashboardPage() {
  const session = await auth.api.getSession({ headers: await headers() }); const cards = await db.select().from(invitations).where(eq(invitations.userId, session!.user.id)).orderBy(desc(invitations.updatedAt))
  return <main className="mx-auto flex max-w-6xl flex-col gap-8 px-5 py-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-widest text-primary">Studio jemputan</p><h1 className="mt-2 font-serif text-4xl text-balance">Raikan setiap kisah cinta</h1><p className="mt-2 text-muted-foreground">Cipta, sunting dan terbitkan jemputan anda dari satu tempat.</p></div><form action={createInvitation} className="flex gap-2"><input name="title" required placeholder="Nama jemputan" className="h-11 rounded-xl border bg-card px-4"/><button className="flex h-11 items-center gap-2 rounded-xl bg-primary px-4 font-semibold text-primary-foreground"><Plus className="size-4"/>Cipta</button></form></div>
  {cards.length === 0 ? <section className="rounded-3xl border border-dashed bg-card p-12 text-center"><p className="font-serif text-2xl">Belum ada jemputan</p><p className="mt-2 text-muted-foreground">Mulakan dengan memberi nama pada jemputan pertama anda.</p></section> : <section className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{cards.map(card => <article key={card.id} className="overflow-hidden rounded-2xl border bg-card"><div className="h-32 p-5" style={{backgroundColor: card.config.theme.background, color: card.config.theme.text}}><p className="text-xs uppercase tracking-widest">{card.status === 'published' ? 'Diterbitkan' : 'Draf'}</p><p className="mt-5 font-serif text-2xl">{card.config.couple.bride} <span className="italic">&</span> {card.config.couple.groom}</p></div><div className="flex flex-col gap-4 p-5"><div><h2 className="font-semibold">{card.title}</h2><p className="text-sm text-muted-foreground">/{card.slug}</p></div><div className="flex items-center gap-2"><Link href={`/dashboard/${card.id}`} className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground"><Settings2 className="size-4"/>Sunting</Link>{card.status === 'published' && <Link aria-label="Lihat jemputan" href={`/i/${card.slug}`} target="_blank" className="rounded-lg border p-2"><ExternalLink className="size-4"/></Link>}</div><form action={setPublish.bind(null, card.id, card.status !== 'published')}><button className="w-full rounded-lg border px-3 py-2 text-sm">{card.status === 'published' ? 'Kembali ke draf' : 'Terbitkan jemputan'}</button></form></div></article>)}</section>}</main>
}
